controllers:
    resource:
        - path: ../src/Controller/Web
          namespace: App\Controller\Web
        - path: ../src/Controller/Api
          namespace: App\Controller\Api
    type: annotation